[package]
name = "application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
api = { path = "../api" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
